name: CI/CD Student App

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/student-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to EC2
        run: |
          echo "${{ secrets.AWS_KEY }}" > key.pem
          chmod 600 key.pem

          ssh -o StrictHostKeyChecking=no -i key.pem \
          ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'

          set -e

          docker network create app_network || true

          # ---------- MYSQL ----------
          if ! docker ps --format '{{.Names}}' | grep -q mysql-db; then
            docker run -d \
              --name mysql-db \
              --network app_network \
              -e MYSQL_ROOT_PASSWORD=root \
              -e MYSQL_DATABASE=attendance_db \
              -v mysql_data:/var/lib/mysql \
              -p 3306:3306 \
              mysql:8.0
            sleep 30
          fi

          until docker exec mysql-db mysqladmin ping -h localhost --silent; do
            sleep 10
          done

          # ---------- BLUE/GREEN SWITCH ----------
          if docker ps --format '{{.Names}}' | grep -q student-app-blue; then
            ACTIVE=blue
            IDLE=green
            IDLE_PORT=5001
          else
            ACTIVE=green
            IDLE=blue
            IDLE_PORT=5000
          fi

          echo "Deploying $IDLE on port $IDLE_PORT"

          docker pull ${{ secrets.DOCKER_USERNAME }}/student-app:latest

          docker rm -f student-app-$IDLE || true

          docker run -d \
            --name student-app-$IDLE \
            --network app_network \
            -p $IDLE_PORT:5000 \
            -e DB_HOST=mysql-db \
            -e DB_USER=root \
            -e DB_PASSWORD=root \
            -e DB_NAME=attendance_db \
            ${{ secrets.DOCKER_USERNAME }}/student-app:latest

          # Switch Nginx traffic
          sudo sed -i "s|localhost:[0-9]*|localhost:$IDLE_PORT|g" /etc/nginx/conf.d/bluegreen.conf
          sudo nginx -s reload

          # Cleanup old active container
          docker rm -f student-app-$ACTIVE || true

          echo "Deployment completed successfully"

          EOF
